version: '3.8'
 
services:

  mariadb:
    image: mariadb:10.8.6
    volumes:
      - ./backend/db/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: axa-coin
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: 1234
    networks:
      - axa-coin
 
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb
    networks:
      - axa-coin

  axa-coin-be:
    image: fixihans/axa-coin-be:latest
    ports:
      - "8080:8080"
    networks:
      - axa-coin
    
  axa-coin-fe:
    image: jayslrs/axa-coin-fe:latest
    ports:
      - "3000:80"
    networks:
      - axa-coin

networks:
  axa-coin:
    driver: bridge